[package]
name = "cis-skill-sdk-derive"
version = "1.1.2"
edition = "2021"
description = "CIS Skill SDK derive macros"
license = "MIT"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full", "derive"] }
